server:
  port: 8086

spring:
  application:
    name: user-server01-8085
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.88.20:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        enabled: true
        register-enabled: true
    ## Sentinel 相关配置
    sentinel:
      filter:
        ## 关闭对SpringMVC端点的保护
        enabled: false
      ## 取消懒加载
      eager: true
      transport:
        ## 指定sentinel控制台地址
        dashboard: http://192.168.88.20:8099

## ------------------------ Ribbon 相关配置
ribbon:
  eager-load:
    enabled: true
    clients: order-server01 # Ribbon 饥饿加载, 服务提供方的服务名

## ------------------------ fegin 相关配置
feign:
  client:
  httpclient:
    # 让Feign使用apache httpclient做请求; 而不是默认的 urlconnection
    enabled: true
    # Feign的做大连接数
    max-connections: 200
    # Feign单个路径的最大连接数
    max-connections-per-route: 50
  # 为 feign 整合 sentinel
  sentinel:
    enabled: true

## ------------------------ web actuator 相关设置
management:
  endpoints:
    web:
      exposure:
        include: '*'

