server:
  port: 8050

spring:
  application:
    name: nacos-server01-8050
  profiles:
    active: dev
  cloud:
    ## nacos 注册中心
    nacos:
      discovery:
        ## nacos 注册地址
        server-addr: http://192.168.88.20:8848
        username: nacos
        password: nacos
        enabled: true
        group: DEFAULT_GROUP
        register-enabled: true

## Ribbon 相关配置
ribbon:
  eager-load:
    enabled: true #
    clients: user-server01-8085 # Ribbon 饥饿加载, 服务提供方的服务名

# fegin 相关配置
feign:
  client:
  httpclient:
    # 让Feign使用apache httpclient做请求; 而不是默认的 urlconnection
    enabled: true
    # Feign的做大连接数
    max-connections: 200
    # Feign单个路径的最大连接数
    max-connections-per-route: 50
#    config:
#      # 想要调用的微服务名称 | default: 全局配置
#      user-server01:
#        loggerLevel: basic


## 日志配置
logging:
  level:
    # Feign日志配置 com.cy.configuration.feignconfig
    com.cy.orderserver01.feignclient.UserFeignClient: debug