server:
  port: 8060

spring:
  application:
    name: elasticsearch-server01-8060
  profiles:
    active: dev

## 日志配置
logging:
  level:
    # Feign日志配置 com.cy.configuration.feignconfigdebug
    com.cy.orderserver01.feignclient.UserFeignClient: